function [trim] = nsd_trimPRFs(vox)
%function [trim] = nsd_trimPRFs(vox)
% like previous trimPRFs function, but optimized for new nsd data. assumes
% everything is already in dva

stimSize = 8.4;                 % nsd stims are x * x dva squares 
minSize = 0.1;                  % in deg, size = [SD/sqrt(N)]
minEccen = 0.1;                 % in deg, usually corresponds to fixation
maxSize = stimSize;             % in deg
maxSD= maxSize;                 % trim whole-field SD estimates (in addition to size)
maxGain = 99;                   % range was set at 100
                
if      isempty(vox.r2)...
        || vox.eccen < minEccen  ...
        || vox.size < minSize ...
        || vox.size > maxSize ...
        || vox.sdDeg > maxSD ...
        || vox.gain > maxGain ...
        || vox.Xdeg > stimSize/2 ...
        || vox.Xdeg < -stimSize/2 ...
        || vox.Ydeg > stimSize/2 ...
        || vox.Ydeg < -stimSize/2 ...
    trim = 1;
else
trim = 0; end

end

